language: node_js
node_js:
 - "node"

cache: npm

script: ./build.sh

deploy:
 provider: pages
 skip_cleanup: true
 github_token: $GITHUB_TOKEN
 local_dir: vue/dist
 on:
   branch: master
